name: task_app
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter_rating_bar: ^4.0.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  modal_progress_hud_nsn: ^0.5.1
  logger:
  fpdart:
  # fluttertoast:


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/category.svg
    - assets/icons/favorite_icon.svg
    - assets/icons/favorite.svg
    - assets/icons/not_favorite.svg
    - assets/icons/orders.svg
    - assets/icons/person.svg
    - assets/icons/product.svg
    - assets/icons/settings.svg
    - assets/icons/support.svg
    
    - assets/images/
    - assets/images/phone.png
    - assets/images/splash_bg.png
    - assets/images/thumbnail.jpg

  